import { RestApi } from '@servicenow/sdk/core'

RestApi({
    $id: Now.ID['3951f792a6884c61aa90674c3e6df975'],
    name: 'Now Code API',
    consumes: 'application/json',
    produces: 'application/json',
    serviceId: 'now_code_api',
    shortDescription: 'REST API for Now Code chat sessions, SDD workflow, and platform introspection',
    routes: [
        {
            $id: Now.ID['08727c3ccd45438588d6f1bde28d62ed'],
            name: 'List Sessions',
            consumes: 'application/json',
            script: Now.include('./operations/list-sessions.js'),
            produces: 'application/json',
            path: '/sessions',
            shortDescription: 'List all sessions for the current user, active first then archived',
        },
        {
            $id: Now.ID['2c9c3dec476743189f8871f037b5dff4'],
            name: 'Reject Artifact',
            consumes: 'application/json',
            method: 'POST',
            script: Now.include('./operations/reject-artifact.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}/artifacts/{artifact_id}/reject',
            shortDescription: 'Reject an SDD proposal artifact. Body: { reason? }',
        },
        {
            $id: Now.ID['383e738a724d4aed95175b7694b10575'],
            name: 'Create Session',
            consumes: 'application/json',
            method: 'POST',
            script: Now.include('./operations/create-session.js'),
            produces: 'application/json',
            path: '/sessions',
            shortDescription: 'Create a new chat session. Body: { name, model?, context_scope? }',
        },
        {
            $id: Now.ID['52906d7fe2e44c89af401ea9aa94c267'],
            name: 'List Models',
            consumes: 'application/json',
            script: Now.include('./operations/list-models.js'),
            produces: 'application/json',
            path: '/models',
            shortDescription: 'List the models served by the configured provider (OpenCode Go by default)',
        },
        {
            $id: Now.ID['632bd773b6c242ed9b05693cfd30f7d1'],
            name: 'Approve Artifact',
            consumes: 'application/json',
            method: 'POST',
            script: Now.include('./operations/approve-artifact.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}/artifacts/{artifact_id}/approve',
            shortDescription: 'Approve an SDD proposal artifact to unlock the spec phase',
        },
        {
            $id: Now.ID['83ccef9013e94a6f9624b823d0cb5a0b'],
            name: 'Send Message',
            consumes: 'application/json',
            method: 'POST',
            script: Now.include('./operations/send-message.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}/messages',
            shortDescription: 'Send a message in a session. Body: { content, sdd_command?, target_table?, targe',
        },
        {
            $id: Now.ID['9618de0df6c64a7a997573096f5614ab'],
            name: 'Get Session',
            consumes: 'application/json',
            script: Now.include('./operations/get-session.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}',
            shortDescription: 'Get session details including SDD status if active',
        },
        {
            $id: Now.ID['9c9228a0b31049e28b9082e28948d28d'],
            name: 'Get Messages',
            consumes: 'application/json',
            script: Now.include('./operations/get-messages.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}/messages',
            shortDescription: 'Get chat message history for a session with pagination',
            parameters: [
                {
                    $id: Now.ID['e8a76a28d35c40018d06eebcc6ce864b'],
                    name: 'offset',
                    shortDescription: 'Offset for pagination (default: 0)',
                },
                {
                    $id: Now.ID['a8752229a65c4c61890902e67dffb004'],
                    name: 'limit',
                    shortDescription: 'Maximum number of messages to return (default: 50)',
                },
            ],
        },
        {
            $id: Now.ID['b819b6a3484f4946bd6514173ce1444e'],
            name: 'Get Table Schema',
            consumes: 'application/json',
            script: Now.include('./operations/get-table-schema.js'),
            produces: 'application/json',
            path: '/platform/tables/{table_name}/schema',
            shortDescription: 'Get the full schema for a table including fields, types, and constraints',
        },
        {
            $id: Now.ID['c16fd2e784f9416ba4c55d20eeef3bab'],
            name: 'Get Artifacts',
            consumes: 'application/json',
            script: Now.include('./operations/get-artifacts.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}/artifacts',
            shortDescription: 'Get all SDD artifacts for a session',
        },
        {
            $id: Now.ID['ce7de2ab5e854fcba70ed65657edbd8f'],
            name: 'Archive Session',
            consumes: 'application/json',
            method: 'DELETE',
            script: Now.include('./operations/archive-session.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}',
            shortDescription: 'Archive a session (sets status to archived)',
        },
        {
            $id: Now.ID['dc738d9b309542e3bfca2c88370fe4cb'],
            name: 'Search Tables',
            consumes: 'application/json',
            script: Now.include('./operations/search-tables.js'),
            produces: 'application/json',
            path: '/platform/tables',
            shortDescription: 'Search platform tables, optionally filtered by scope',
            parameters: [
                {
                    $id: Now.ID['f07c344e61fc42a6b06583e63ca988ac'],
                    name: 'scope',
                    shortDescription: 'Application scope to filter tables (e.g. x_1733631_now_code)',
                },
            ],
        },
        {
            $id: Now.ID['now_code_api_get_settings'],
            name: 'Get Settings',
            consumes: 'application/json',
            script: Now.include('./operations/get-settings.js'),
            produces: 'application/json',
            path: '/settings',
            shortDescription: 'Current user LLM provider settings (never returns the API key itself)',
        },
        {
            $id: Now.ID['now_code_api_update_settings'],
            name: 'Update Settings',
            consumes: 'application/json',
            method: 'PUT',
            script: Now.include('./operations/update-settings.js'),
            produces: 'application/json',
            path: '/settings',
            shortDescription:
                'Save LLM provider settings. Body: { provider?, api_key?, clear_api_key?, base_url?, default_model?, max_tokens? }',
        },
        {
            $id: Now.ID['now_code_api_test_connection'],
            name: 'Test Connection',
            consumes: 'application/json',
            method: 'POST',
            script: Now.include('./operations/test-connection.js'),
            produces: 'application/json',
            path: '/settings/test',
            shortDescription: 'Verify the stored API key by listing models and sending a tiny prompt',
        },
        {
            $id: Now.ID['now_code_api_update_session'],
            name: 'Update Session',
            consumes: 'application/json',
            method: 'PATCH',
            script: Now.include('./operations/update-session.js'),
            produces: 'application/json',
            path: '/sessions/{session_id}',
            shortDescription: 'Update a session. Body: { name?, model?, context_scope? }',
        },
        {
            $id: Now.ID['now_code_api_list_warranty_requests'],
            name: 'List Warranty Requests',
            consumes: 'application/json',
            script: Now.include('./operations/list-warranty-requests.js'),
            produces: 'application/json',
            path: '/warranty/requests',
            shortDescription: 'Warranty requested items with primary and current SLA progress',
            parameters: [
                {
                    $id: Now.ID['now_code_api_warranty_param_state'],
                    name: 'state',
                    shortDescription: 'open (default), closed or all',
                },
                {
                    $id: Now.ID['now_code_api_warranty_param_q'],
                    name: 'q',
                    shortDescription: 'Search by RITM/REQ number, requested for or description',
                },
                {
                    $id: Now.ID['now_code_api_warranty_param_limit'],
                    name: 'limit',
                    shortDescription: 'Maximum rows (default 200, max 500)',
                },
            ],
        },
        {
            $id: Now.ID['now_code_api_get_warranty_request'],
            name: 'Get Warranty Request',
            consumes: 'application/json',
            script: Now.include('./operations/get-warranty-request.js'),
            produces: 'application/json',
            path: '/warranty/requests/{ritm_id}',
            shortDescription: 'One warranty requested item with every SLA, catalog tasks and variables',
        },
    ],
})
